baseURL: https://anttikoistinen.fi/
title: Antti Koistinen
theme: PaperMod
copyright: Antti Koistinen Â© 2025

# setting page language to Finnish
defaultContentLanguage: fi
defaultContentLanguageInSubdir: false
languageCode: fi-FI
languages:
  fi:
    languageName: "Suomi"
    weight: 1
  en:
    languageName: "English"
    weight: 2

      

sectionPagesMenu: main
pluralizeListTitles: false

params:
  profileMode:
    enabled: true
    #title: "<Title>" # optional default will be site title
    #subtitle: "This is subtitle"
    imageUrl: "/Antti.png" # optional
    imageTitle: "Antti Koistinen" # optional
    imageWidth: 250 # custom size
    imageHeight: 250 # custom size
    buttons: 
      #- name: Antti
      #  url: "/about"
      #- name: Q-Itu Solutions
      #  url: "/q-itu"


  
  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/anttikoistinen/"
    #- name: "Instagram"
    #  url: "https://www.instagram.com/ajkoistinen/"
    - name: "Bluesky"
      url: "https://bsky.app/profile/anttikoistinen.fi"
    #- name: "Facebook"
    #  url: "https://www.facebook.com/antti.j.koistinen"
  
  assets:
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/apple-touch-icon.png"
    customCSS:
      - css/custom.css

  images: ["img/anttikoistinen-cover.png"]